<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="45.0250" tests="4" failures="5">
  <testsuite name="Root Suite" timestamp="2022-12-26T06:56:03" tests="0" time="0.0000" failures="1">
    <testcase name=" Uncaught error outside test suite" time="0.0000" classname="Uncaught error outside test suite">
      <failure message="listen EADDRINUSE :::9000" type="Error"><![CDATA[Error: listen EADDRINUSE :::9000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (node_modules/express/lib/application.js:635:24)
    at Object.<anonymous> (testserver.js:35:7)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (test/test.js:7:14)
    at require (internal/module.js:11:18)
    at Array.forEach (<anonymous>)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="Preparing to test API" timestamp="2022-12-26T06:56:03" tests="0" file="/projects/challenge/test/test.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="API testing started" timestamp="2022-12-26T06:56:03" tests="4" file="/projects/challenge/test/test.js" time="45.0250" failures="4">
    <testcase name="Preparing to test API API testing started it should test prob1 API" time="0.0000" classname="it should test prob1 API">
      <failure message="ENOENT: no such file or directory, open &apos;data.csv&apos;" type="Error"><![CDATA[Error: ENOENT: no such file or directory, open 'data.csv']]></failure>
    </testcase>
    <testcase name="Preparing to test API API testing started it should test prob2 API" time="10.0010" classname="it should test prob2 API">
      <failure message="timeout of 10000ms exceeded. Ensure the done() callback is being called in this test." type="Error"><![CDATA[Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.]]></failure>
    </testcase>
    <testcase name="Preparing to test API API testing started it should test prob3 API" time="10.0100" classname="it should test prob3 API">
      <failure message="timeout of 10000ms exceeded. Ensure the done() callback is being called in this test." type="Error"><![CDATA[Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.]]></failure>
    </testcase>
    <testcase name="Preparing to test API API testing started it should test prob 4 API" time="25.0140" classname="it should test prob 4 API">
      <failure message="timeout of 25000ms exceeded. Ensure the done() callback is being called in this test." type="Error"><![CDATA[Error: timeout of 25000ms exceeded. Ensure the done() callback is being called in this test.]]></failure>
    </testcase>
  </testsuite>
</testsuites>